version: 2

jobs:
  get_source:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - checkout
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/sylabs/slurm-operator

  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Build red-box
          command: make

  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Unit tests
          command: make test

  lint:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Install golangci-lint v1.15
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
      - run:
          name: Linters
          command: make lint

  publish:
    machine: true
    steps:
      - attach_workspace:
          at: ~/go
      - run:
          name: Setup environment
          command: |
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
            echo 'export PATH=$PATH:$GOPATH/bin:$GOROOT/bin' >> $BASH_ENV
            echo 'export PATH=$PATH:/usr/local/libexec/singularity/bin/' >> $BASH_ENV
      - run:
          name: Update go to 1.12
          working_directory: /tmp
          command: |
            wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.12.linux-amd64.tar.gz
      - run:
          name: Install dev libraries
          command: |
            sudo apt-get update -y
            sudo apt-get install -y build-essential libssl-dev uuid-dev squashfs-tools libseccomp-dev libgpgme11-dev
      - run:
          name: Install singularity
          command: |
            git clone https://github.com/sylabs/singularity.git $GOPATH/src/github.com/sylabs/singularity
            cd $GOPATH/src/github.com/sylabs/singularity
            ./mconfig -p /usr/local
            make -j$(nproc) -C ./builddir
            sudo make -C ./builddir install
      - run:
          name: Authorize remote library
          command: |
            echo $SYLABS_TOKEN >> token
            singularity remote login SylabsCloud --tokenfile token
      - run:
          name: Publish images
          command: |
            cd $GOPATH/src/github.com/sylabs/slurm-operator
            make push

workflows:
  version: 2
  build_test_publish:
    jobs:
      - get_source
      - build:
          requires:
            - get_source
      - test:
          requires:
            - get_source
      - lint:
          requires:
            - get_source
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - test
            - lint
